language: csharp
solution: ./src/holmescode.com.csproj
mono: none
dotnet: 1.0.1
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine  

script:
  - dotnet restore ./src/holmescode.com.csproj
  - dotnet build ./src/holmescode.com.csproj -c Release -o ./src/build
  - docker build -t mattholmes/website .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mattholmes/website
