language: csharp
solution: ./src/holmescode.com.csproj
mono: none
dotnet: 1.0.1
dist: trusty

before_install:  
  - sudo apt-get remove docker docker-engine
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - sudo docker --version

script:
  - dotnet restore $TRAVIS_BUILD_DIR/src/holmescode.com.csproj
  - dotnet build $TRAVIS_BUILD_DIR/src/holmescode.com.csproj -c Release -o $TRAVIS_BUILD_DIR/src/build
  - ls $TRAVIS_BUILD_DIR/src
  - ls $TRAVIS_BUILD_DIR/src/build
  - docker build -t mattholmes/website:latest .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mattholmes/website:latest
